version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/home/deploy/myapp_static/static
      - ./:/MyProjectDjango  # Для разработки - монтируем код
    environment:
      - DJANGO_SETTINGS_MODULE=store.settings
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - POSTGRES_HOST=app-postgres
      - POSTGRES_DB=django_app
      - POSTGRES_USER=django_app
      - POSTGRES_PASSWORD=django_app
    depends_on:
      app-postgres:
        condition: service_healthy
    restart: unless-stopped

  app-postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django_app
      POSTGRES_USER: django_app
      POSTGRES_PASSWORD: django_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_app -d django_app"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
