# Generated by Django 4.2.20 on 2025-05-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_products_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='role',
        ),
        migrations.RemoveField(
            model_name='products',
            name='warehouses',
        ),
        migrations.AddField(
            model_name='products',
            name='roles',
            field=models.ManyToManyField(related_name='products', to='myapp.role'),
        ),
    ]
