# Generated by Django 4.2.20 on 2025-05-04 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_roles_products_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='role',
            field=models.ManyToManyField(related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
