# Generated by Django 4.2.20 on 2025-05-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_products_role_products_warehouses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='warehouses',
        ),
    ]
