# Generated by Django 4.2.20 on 2025-05-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_products_role_remove_products_warehouses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='roles',
            new_name='role',
        ),
    ]
