# Generated by Django 4.2.20 on 2025-05-04 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_products_warehouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='warehouses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouse'),
            preserve_default=False,
        ),
    ]
