# Generated by Django 4.2.20 on 2025-05-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_products_warehouses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
