name: Docker Build & Deploy

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        run: |
          docker build -t "${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}" -t "${{ env.REGISTRY }}/${{ github.repository }}:latest" .
          docker push "${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}"
          docker push "${{ env.REGISTRY }}/${{ github.repository }}:latest"

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo su
            cd django_build
            sudo apt install nginx -y
            sudo rm /etc/nginx/sites-enabled/default
            sudo ln -s /home/deploy/django_build/conf/myapp.nginx /etc/nginx/sites-enabled/
            sudo ln -s /etc/nginx/sites-enabled/myapp.nginx /etc/nginx/sites-available/
            sudo systemctl restart nginx
            sudo docker-compose pull
            sudo docker-compose up -d
