name: Pylint Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pylint-django
    
    - name: Find Python files and run Pylint
      run: |
        # Игнорируем миграции и виртуальные окружения
        python_files=$(find . -name "*.py" -not -path "./migrations/*" \
                                      -not -path "./venv/*" \
                                      -not -path "./.venv/*")
        
        if [ -z "$python_files" ]; then
          echo "No Python files found to lint"
          exit 0
        fi
        
        echo "Running Pylint on:"
        echo "$python_files"
        
        # Запускаем Pylint для каждого файла отдельно
        for file in $python_files; do
          pylint --load-plugins pylint_django \
                 --rcfile=.pylintrc \
                 "$file" || true
        done
        
